apiVersion: gravitee.io/v1alpha1
kind: ManagementContext
metadata:
  name: apim-blue
spec:
  auth:
    bearerToken: b79f1a1a-917c-4f19-9f1a-1a917c3f1925
  baseUrl: http://apim-blue-apim3-api.apim-blue.svc:83
  environmentId: DEFAULT
  organizationId: DEFAULT
