apiVersion: gravitee.io/v1alpha1
kind: ManagementContext
metadata:
  name: apim-blue
spec:
  auth:
    bearerToken: 01b72c2f-f798-4d76-b72c-2ff7986d769c
  baseUrl: http://apim-blue-apim3-api.apim-blue.svc:83
  environmentId: DEFAULT
  organizationId: DEFAULT
